name: Combine Swagger UI and Auto Merge
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  combineSwagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Swagger Combine
        run: |
          npm install -g swagger-combine

      - name: Combine Swagger YAML Files
        run: |
          swagger-combine swagger-combine.yml -o swagger.yml

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Check for Changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_ENV

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Combine swaggers
          title: Update swagger.yml to combine all swaggers
          body: |
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: combine-swagger-updates

      - name: Enable Pull Request Automerge
        if: steps.create_pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
          merge-method: squash