name: Combine Swagger UI and Auto Merge
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  combineSwagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Swagger Combine
        run: |
          npm install -g swagger-combine

      - name: Combine Swagger YAML Files
        run: |
          swagger-combine swagger-combine.yml -o swagger.yml

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Check for Existing Pull Request
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(gh pr list --head combine-swagger-updates --state open --json number --jq '.[0].number')
          echo "pr_number=$pr_number" >> $GITHUB_ENV

      - name: Update Existing Pull Request
        id: update_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.pr_number != ''
        run: |
          git checkout combine-swagger-updates
          git add swagger.yml
          git commit -m "Update Swagger files"
          git push origin combine-swagger-updates

      - name: Create Pull Request
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.pr_number == ''
        run: |
          gh pr create --head combine-swagger-updates --title "Combine Swagger UI" --body "This updates the Swagger files with the latest combined specification."

      - name: Merge Pull Request
        id: merge_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ env.pr_number }}" ]; then
            gh pr merge ${{ env.pr_number }} --admin --squash --delete-branch
          fi